declare module "*cors"
declare module "*express"
declare module "*mongoose"
declare module "*ejs"
declare module "*axios"
declare module "*googleapis";
declare module "*bcrypt";
declare module "*uuid";
declare module "*jsonwebtoken";
declare module "*nodemailer";
declare module "*cloudinary";
declare module "*cookie-session";
declare module "*multer";
declare module "*dotenv";
declare module "*validator";
declare module "*swagger-jsdoc";
declare module "*node-fetch";